/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Audit */
        get: operations["list_audit_api_audit_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/correspondents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Correspondents */
        get: operations["list_correspondents_api_entities_correspondents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/document_types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Document Types */
        get: operations["list_document_types_api_entities_document_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_entities_documents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/documents/{doc_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_entities_documents__doc_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/documents/{doc_id}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thumbnail */
        get: operations["get_thumbnail_api_entities_documents__doc_id__thumb_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/storage_paths": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Storage Paths */
        get: operations["list_storage_paths_api_entities_storage_paths_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_api_entities_tags_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_type}/merge-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Merge Candidates
         * @description Deterministic duplicate pre-pass over one taxonomy: pairs whose
         *     names are close by string distance or embedding cosine. The agent
         *     (or the human) adjudicates; this only finds candidates.
         */
        get: operations["get_merge_candidates_api_entities__entity_type__merge_candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_type}/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entity
         * @description Generic taxonomy entity detail (documents have their own route).
         */
        get: operations["get_entity_api_entities__entity_type___entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_type}/{entity_id}/instructions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Instructions
         * @description Set the app-local agent instructions for a taxonomy entity.
         *     Clearing stores an empty row — seeded defaults never come back.
         */
        put: operations["put_instructions_api_entities__entity_type___entity_id__instructions_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description Cancel all still-pending work of a job. Running steps finish.
         */
        post: operations["cancel_job_api_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/prefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Prefs */
        get: operations["get_prefs_api_prefs_get"];
        /** Put Prefs */
        put: operations["put_prefs_api_prefs_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proposals */
        get: operations["list_proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proposal */
        get: operations["get_proposal_api_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Proposal
         * @description Set/replace the user-edited payload. The body is the FULL
         *     replacement payload (not a merge — so agent-proposed fields can be
         *     dropped); `kind` is enforced server-side. The agent original stays
         *     immutable; pass user_payload=null to discard edits.
         */
        patch: operations["patch_proposal_api_proposals__proposal_id__patch"];
        trace?: never;
    };
    "/api/proposals/{proposal_id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply */
        post: operations["apply_api_proposals__proposal_id__apply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/revert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revert */
        post: operations["revert_api_proposals__proposal_id__revert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/revert-check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Revert Check
         * @description Would reverting this applied proposal change anything? Drives the
         *     greyed-out Revert button (noop reverts are refused server-side too).
         */
        get: operations["revert_check_api_proposals__proposal_id__revert_check_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sessions
         * @description Paginated session list, filterable by bound entity. Active and
         *     archived sessions are separate lists (archived=true for the
         *     latter); unfinished=true keeps only sessions that still need
         *     something (gates, running/queued work, failures — or proposals
         *     still waiting for review).
         */
        get: operations["list_sessions_api_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/analyze/document/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Document
         * @description Start a document analysis. Even a single analysis is a tracked
         *     job (total=1); it runs on the interactive lane.
         */
        post: operations["analyze_document_api_sessions_analyze_document__document_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/analyze/{entity_type}/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Entity
         * @description Start a taxonomy review session (tag/correspondent/document_type).
         *     The inbox tag is a workflow marker, not a label — analyzing it for
         *     applicability is meaningless and refused.
         */
        post: operations["analyze_entity_api_sessions_analyze__entity_type___entity_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Detail */
        get: operations["get_session_detail_api_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Session
         * @description Archive: leaves the active lists, refuses forward-apply and new
         *     steps. The journal keeps working — applied changes stay revertible
         *     (you can always go BACK to a state, just not forward-apply).
         */
        post: operations["archive_session_api_sessions__session_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session Events
         * @description SSE stream: step_changed (invalidation signal) + step_progress
         *     (live tokens/tools). Tiny payloads; clients refetch over REST.
         */
        get: operations["session_events_api_sessions__session_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send Message
         * @description Steer a session: append a chat step. Non-blocking — progress
         *     arrives via the SSE stream.
         */
        post: operations["send_message_api_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/ocr": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Ocr Review
         * @description The OCR gate's diff data: current paperless content vs. new OCR.
         */
        get: operations["get_ocr_review_api_sessions__session_id__ocr_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/steps/{step_id}/redo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redo Step
         * @description Generic redo: supersede the step and run a fresh one, optionally
         *     with amended input (e.g. OCR re-run with instructions).
         */
        post: operations["redo_step_api_sessions__session_id__steps__step_id__redo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/steps/{step_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Step
         * @description Resolve an awaiting_user step (the OCR gate: content=None keeps
         *     the existing text, a string is the accepted/hand-fixed version).
         */
        post: operations["resolve_step_api_sessions__session_id__steps__step_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/steps/{step_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retry Step
         * @description Generic retry-now: skip a scheduled backoff or revive a failed
         *     step with a fresh auto-retry budget. Never limited.
         */
        post: operations["retry_step_api_sessions__session_id__steps__step_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{session_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Session */
        post: operations["unarchive_session_api_sessions__session_id__unarchive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings Overview */
        get: operations["get_settings_overview_api_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stats */
        get: operations["stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sync/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync Status
         * @description When the app last fetched each paperless resource and whether a
         *     fetch is in flight RIGHT NOW — covers every consumer in the process
         *     (UI proxying, agent tools, pipeline stages).
         */
        get: operations["sync_status_api_sync_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/webhooks/paperless": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Paperless Webhook */
        post: operations["paperless_webhook_api_webhooks_paperless_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AgentKind
         * @enum {string}
         */
        AgentKind: "document" | "tag" | "correspondent" | "document_type";
        /** AnalyzeEntityRequest */
        AnalyzeEntityRequest: {
            /** Instructions */
            instructions?: string | null;
        };
        /** AnalyzeRequest */
        AnalyzeRequest: {
            /** Instructions */
            instructions?: string | null;
            /**
             * Redo Ocr
             * @default false
             */
            redo_ocr: boolean;
        };
        /**
         * AttemptRecord
         * @description One entry of a step's attempt log (never shadowed by retries).
         */
        AttemptRecord: {
            /** Attempt */
            attempt?: number | null;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Manual Retry At */
            manual_retry_at?: string | null;
            /** Started At */
            started_at?: string | null;
        };
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Action */
            action: string;
            /**
             * Actor
             * @default system
             */
            actor: string;
            /**
             * Detail
             * @default {}
             */
            detail: {
                [key: string]: unknown;
            };
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /** Ts */
            ts: string;
        };
        /** AuditPage */
        AuditPage: {
            /** Count */
            count: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Results */
            results: components["schemas"]["AuditEntryOut"][];
        };
        /** AuthMeOut */
        AuthMeOut: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "none" | "proxy" | "paperless";
            /** User */
            user?: string | null;
        };
        /**
         * CallTiming
         * @description Per-LLM-call metrics, stamped by the TimedModel wrapper.
         */
        CallTiming: {
            /** Duration S */
            duration_s?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Started At */
            started_at?: string | null;
            /** Tps */
            tps?: number | null;
            /** Ttft S */
            ttft_s?: number | null;
        };
        /**
         * DocumentOut
         * @description Document list/detail item (content only on detail).
         */
        DocumentOut: {
            /** Added */
            added?: string | null;
            /** Archive Serial Number */
            archive_serial_number?: number | null;
            /** Content */
            content?: string | null;
            /** Correspondent */
            correspondent?: number | null;
            /** Created */
            created?: string | null;
            /** Document Type */
            document_type?: number | null;
            /** Id */
            id: number;
            /** Modified */
            modified?: string | null;
            /** Original File Name */
            original_file_name?: string | null;
            /** Storage Path */
            storage_path?: number | null;
            /**
             * Tags
             * @default []
             */
            tags: number[];
            /**
             * Title
             * @default
             */
            title: string;
        };
        /**
         * DocumentSearchPage
         * @description Proxied paperless search: ``all`` carries every matching id
         *     across pages (drives cross-page select-all).
         */
        DocumentSearchPage: {
            /** All */
            all?: number[] | null;
            /** Count */
            count: number;
            /**
             * Page Size
             * @default 25
             */
            page_size: number;
            /** Results */
            results: components["schemas"]["DocumentOut"][];
        };
        /**
         * EntityOut
         * @description Taxonomy entity as the UI sees it: paperless fields + the
         *     app-local agent instructions.
         */
        EntityOut: {
            /** Color */
            color?: string | null;
            /** Document Count */
            document_count?: number | null;
            /** Id */
            id: number;
            /**
             * Instructions
             * @default
             */
            instructions: string;
            /**
             * Is Inbox Tag
             * @default false
             */
            is_inbox_tag: boolean;
            /**
             * Match
             * @default
             */
            match: string;
            /**
             * Matching Algorithm
             * @default 0
             */
            matching_algorithm: number;
            /** Name */
            name: string;
            /** Path */
            path?: string | null;
        };
        /** EntityRefOut */
        EntityRefOut: {
            /** Document Count */
            document_count?: number | null;
            /** Id */
            id: number;
            /** Name */
            name: string;
        };
        /**
         * EntityType
         * @enum {string}
         */
        EntityType: "document" | "tag" | "correspondent" | "document_type" | "storage_path";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /** Status */
            status: string;
        };
        /** InstructionsOut */
        InstructionsOut: {
            /** Entity Id */
            entity_id: number;
            /** Entity Type */
            entity_type: string;
            /** Instructions */
            instructions: string;
        };
        /** InstructionsUpdate */
        InstructionsUpdate: {
            /**
             * Instructions
             * @default
             */
            instructions: string;
        };
        /**
         * JobCreate
         * @description Bulk job. The work set is deterministic: explicit document ids,
         *     a tag, the inbox, all untagged documents — or a set of taxonomy
         *     entities (entity_type + entity_ids) — never a full-text search.
         */
        JobCreate: {
            /**
             * Apply Policy
             * @default review
             * @enum {string}
             */
            apply_policy: "review" | "auto";
            /** Document Ids */
            document_ids?: number[] | null;
            /** Entity Ids */
            entity_ids?: number[] | null;
            /** Entity Type */
            entity_type?: ("tag" | "correspondent" | "document_type") | null;
            /**
             * Inbox
             * @default false
             */
            inbox: boolean;
            /** Instructions */
            instructions?: string | null;
            /**
             * Redo Ocr
             * @default false
             */
            redo_ocr: boolean;
            /** Tag Id */
            tag_id?: number | null;
            /**
             * Untagged Only
             * @default false
             */
            untagged_only: boolean;
        };
        /** JobDetailOut */
        JobDetailOut: {
            /** Created At */
            created_at: string;
            /** Done */
            done: number;
            /** Error */
            error: string | null;
            /** Failed */
            failed: number;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /**
             * Sessions
             * @default []
             */
            sessions: components["schemas"]["SessionOut"][];
            status: components["schemas"]["JobStatus"];
            /** Total */
            total: number;
            /** Updated At */
            updated_at: string;
        };
        /** JobOut */
        JobOut: {
            /** Created At */
            created_at: string;
            /** Done */
            done: number;
            /** Error */
            error: string | null;
            /** Failed */
            failed: number;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            status: components["schemas"]["JobStatus"];
            /** Total */
            total: number;
            /** Updated At */
            updated_at: string;
        };
        /** JobPage */
        JobPage: {
            /** Count */
            count: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Results */
            results: components["schemas"]["JobOut"][];
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "completed" | "failed" | "cancelled";
        /** LoginRequest */
        LoginRequest: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** MergeCandidateOut */
        MergeCandidateOut: {
            /** Entity Type */
            entity_type: string;
            /** Semantic Score */
            semantic_score: number | null;
            source: components["schemas"]["EntityRefOut"];
            /** String Score */
            string_score: number;
            target: components["schemas"]["EntityRefOut"];
        };
        /** MessageRequest */
        MessageRequest: {
            /** Content */
            content: string;
        };
        /** MetaOut */
        MetaOut: {
            /** Paperless Url */
            paperless_url: string;
        };
        /** OcrBatchTiming */
        OcrBatchTiming: {
            /** Duration S */
            duration_s?: number | null;
            /** Finished At */
            finished_at?: string | null;
            /** Input Tokens */
            input_tokens?: number | null;
            /** Output Tokens */
            output_tokens?: number | null;
            /** Pages */
            pages?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Tps */
            tps?: number | null;
            /** Ttft S */
            ttft_s?: number | null;
        };
        /**
         * OcrReviewOut
         * @description Data for the OCR gate diff view. Deliberately excludes internal
         *     scoring (similarity) — the user reviews text, not metrics.
         */
        OcrReviewOut: {
            /** Document Id */
            document_id: number;
            /** Ocr Text */
            ocr_text: string;
            /** Pages */
            pages: number;
            /** Previous Content */
            previous_content: string;
            /**
             * Timings
             * @default []
             */
            timings: components["schemas"]["OcrBatchTiming"][];
        };
        /** PaperlessOut */
        PaperlessOut: {
            /** Auth */
            auth: string;
            /** Base Url */
            base_url: string;
            /** External Url */
            external_url: string;
            /** Timeout Seconds */
            timeout_seconds: number;
        };
        /** PrefsOut */
        PrefsOut: {
            /**
             * Agent Prompt Addition
             * @default
             */
            agent_prompt_addition: string;
            /**
             * Agent Prompt Base
             * @default
             */
            agent_prompt_base: string;
            /**
             * Date Format
             * @default system
             * @enum {string}
             */
            date_format: "system" | "iso" | "eu" | "us";
            /**
             * Ocr Prompt Addition
             * @default
             */
            ocr_prompt_addition: string;
            /**
             * Ocr Prompt Base
             * @default
             */
            ocr_prompt_base: string;
            /**
             * Time Format
             * @default 24h-seconds
             * @enum {string}
             */
            time_format: "24h" | "24h-seconds" | "12h" | "12h-seconds";
            /**
             * Time Zone
             * @default system
             */
            time_zone: string;
        };
        /** PrefsUpdate */
        PrefsUpdate: {
            /** Agent Prompt Addition */
            agent_prompt_addition?: string | null;
            /** Agent Prompt Base */
            agent_prompt_base?: string | null;
            /** Date Format */
            date_format?: ("system" | "iso" | "eu" | "us") | null;
            /** Ocr Prompt Addition */
            ocr_prompt_addition?: string | null;
            /** Ocr Prompt Base */
            ocr_prompt_base?: string | null;
            /** Time Format */
            time_format?: ("24h" | "24h-seconds" | "12h" | "12h-seconds") | null;
            /** Time Zone */
            time_zone?: string | null;
        };
        /** ProfileOut */
        ProfileOut: {
            /**
             * Base Url
             * @default
             */
            base_url: string;
            /**
             * Configured
             * @default true
             */
            configured: boolean;
            /** Max Concurrent */
            max_concurrent?: number | null;
            /** Max Input Tokens */
            max_input_tokens?: number | null;
            /** Max Tool Iterations */
            max_tool_iterations?: number | null;
            /**
             * Model
             * @default
             */
            model: string;
            /** Supports Streaming */
            supports_streaming?: boolean | null;
            /** Thinking */
            thinking?: string | null;
        };
        /** PromptDefaults */
        PromptDefaults: {
            /** Agent Base */
            agent_base: string;
            /** Ocr Base */
            ocr_base: string;
        };
        /** ProposalOut */
        ProposalOut: {
            /** Agent Payload */
            agent_payload: {
                [key: string]: unknown;
            };
            /**
             * Applied
             * @default false
             */
            applied: boolean;
            /** Base Snapshot */
            base_snapshot?: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at: string;
            /** Entity Id */
            entity_id: number | null;
            entity_type: components["schemas"]["EntityType"] | null;
            /** Id */
            id: number;
            /** Kind */
            kind: string;
            /**
             * Reverted
             * @default false
             */
            reverted: boolean;
            /** Revision */
            revision: number;
            /** Session Id */
            session_id: number;
            status: components["schemas"]["ProposalStatus"];
            /** Supersedes Id */
            supersedes_id: number | null;
            /** Updated At */
            updated_at: string;
            /** User Payload */
            user_payload: {
                [key: string]: unknown;
            } | null;
        };
        /** ProposalPage */
        ProposalPage: {
            /** Count */
            count: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Results */
            results: components["schemas"]["ProposalOut"][];
        };
        /** ProposalPatch */
        ProposalPatch: {
            /** User Payload */
            user_payload?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ProposalStatus
         * @enum {string}
         */
        ProposalStatus: "draft" | "pending" | "applying" | "applied" | "superseded" | "no_change";
        /**
         * QueueLane
         * @description Two lanes so chat turns never wait behind bulk work.
         * @enum {string}
         */
        QueueLane: "interactive" | "batch";
        /** QueueOut */
        QueueOut: {
            /** Batch Concurrency */
            batch_concurrency: number;
            /** Interactive Concurrency */
            interactive_concurrency: number;
            /** Retry Attempts */
            retry_attempts: number;
            /** Retry Delay Seconds */
            retry_delay_seconds: number;
        };
        /**
         * RedoRequest
         * @description Amended input for a redo (merged over the original step input) —
         *     e.g. {"instructions": "..."} for an OCR re-run.
         */
        RedoRequest: {
            /** Input */
            input?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * ResolveRequest
         * @description Resolution body for awaiting_user steps. OCR gate: None keeps the
         *     existing content; a string is the accepted (possibly hand-fixed)
         *     text.
         */
        ResolveRequest: {
            /** Content */
            content?: string | null;
        };
        /** ResourceFetch */
        ResourceFetch: {
            /**
             * In Flight
             * @default 0
             */
            in_flight: number;
            /** Last Error */
            last_error?: string | null;
            /** Last Fetched At */
            last_fetched_at?: string | null;
        };
        /** RevertCheckOut */
        RevertCheckOut: {
            /** Revert Noop */
            revert_noop: boolean;
        };
        /** SessionDetailOut */
        SessionDetailOut: {
            agent_kind: components["schemas"]["AgentKind"];
            /** Archived At */
            archived_at?: string | null;
            /** Created At */
            created_at: string;
            /** Entity Id */
            entity_id: number | null;
            entity_type: components["schemas"]["EntityType"] | null;
            /** Error */
            error: string | null;
            /** Id */
            id: number;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            phase: components["schemas"]["SessionPhase"] | null;
            /**
             * Proposal Count
             * @default 0
             */
            proposal_count: number;
            /**
             * Proposals
             * @default []
             */
            proposals: components["schemas"]["ProposalOut"][];
            status: components["schemas"]["SessionStatus"];
            /**
             * Steps
             * @default []
             */
            steps: components["schemas"]["StepOut"][];
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /** SessionOut */
        SessionOut: {
            agent_kind: components["schemas"]["AgentKind"];
            /** Archived At */
            archived_at?: string | null;
            /** Created At */
            created_at: string;
            /** Entity Id */
            entity_id: number | null;
            entity_type: components["schemas"]["EntityType"] | null;
            /** Error */
            error: string | null;
            /** Id */
            id: number;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            phase: components["schemas"]["SessionPhase"] | null;
            /**
             * Proposal Count
             * @default 0
             */
            proposal_count: number;
            status: components["schemas"]["SessionStatus"];
            /** Title */
            title: string;
            /** Updated At */
            updated_at: string;
        };
        /**
         * SessionPage
         * @description Pagination envelope (uniform across all app-owned lists).
         */
        SessionPage: {
            /** Count */
            count: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Results */
            results: components["schemas"]["SessionOut"][];
        };
        /**
         * SessionPhase
         * @description Document-analysis pipeline stage. The OCR review is a GATE: the
         *     pipeline stops there until the user accepts/fixes/skips the OCR
         *     result; only then does the metadata analysis run — on the post-gate
         *     content.
         * @enum {string}
         */
        SessionPhase: "queued" | "ocr_running" | "ocr_review" | "analyzing" | "done";
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "idle" | "running" | "failed";
        /** SettingsOut */
        SettingsOut: {
            /** Auth Mode */
            auth_mode: string;
            /** Database */
            database: string;
            llm_agent: components["schemas"]["ProfileOut"];
            llm_embeddings: components["schemas"]["ProfileOut"];
            llm_ocr: components["schemas"]["ProfileOut"];
            llm_reranker: components["schemas"]["ProfileOut"];
            paperless: components["schemas"]["PaperlessOut"];
            prompt_defaults: components["schemas"]["PromptDefaults"];
            queue: components["schemas"]["QueueOut"];
            webhook: components["schemas"]["WebhookOut"];
        };
        /** StatsOut */
        StatsOut: {
            /** Active Jobs */
            active_jobs: number;
            /** Active Sessions */
            active_sessions: number;
            /**
             * Lifetime
             * @default {}
             */
            lifetime: {
                [key: string]: number;
            };
            /** Pending Proposals */
            pending_proposals: number;
            /** Queue Pending */
            queue_pending: {
                [key: string]: number;
            };
        };
        /**
         * StepKind
         * @enum {string}
         */
        StepKind: "ocr" | "analysis" | "chat";
        /**
         * StepOut
         * @description One timeline element. Generic frame data (state, attempts,
         *     scheduling, timestamps) is uniform across kinds; ``input`` and
         *     ``result`` are kind-specific; agent-turn steps carry their
         *     transcript slice.
         */
        StepOut: {
            /** Attempt Count */
            attempt_count: number;
            /**
             * Attempts
             * @default []
             */
            attempts: components["schemas"]["AttemptRecord"][];
            /** Created At */
            created_at: string;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Id */
            id: number;
            /**
             * Input
             * @default {}
             */
            input: {
                [key: string]: unknown;
            };
            kind: components["schemas"]["StepKind"];
            lane: components["schemas"]["QueueLane"];
            /** Max Attempts */
            max_attempts: number;
            /**
             * Result
             * @default {}
             */
            result: {
                [key: string]: unknown;
            };
            /** Scheduled At */
            scheduled_at: string | null;
            /** Session Id */
            session_id: number;
            /** Started At */
            started_at: string | null;
            state: components["schemas"]["StepState"];
            /** Supersedes Id */
            supersedes_id: number | null;
            /**
             * Transcript
             * @default []
             */
            transcript: components["schemas"]["TranscriptItem"][];
        };
        /**
         * StepState
         * @enum {string}
         */
        StepState: "pending" | "running" | "awaiting_user" | "succeeded" | "failed" | "superseded" | "cancelled";
        /** SyncStatusOut */
        SyncStatusOut: {
            /** Resources */
            resources: {
                [key: string]: components["schemas"]["ResourceFetch"];
            };
        };
        /** TranscriptItem */
        TranscriptItem: {
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Origin
             * @default chat
             * @enum {string}
             */
            origin: "chat" | "pipeline";
            /** Proposal Id */
            proposal_id?: number | null;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "agent" | "tool" | "thinking";
            timing?: components["schemas"]["CallTiming"] | null;
            /** Tool Args */
            tool_args?: {
                [key: string]: unknown;
            } | null;
            /** Tool Name */
            tool_name?: string | null;
            /**
             * Tool Rejected
             * @default false
             */
            tool_rejected: boolean;
            /** Tool Result */
            tool_result?: string | null;
            /** Tool Result Full */
            tool_result_full?: unknown;
            /** Ts */
            ts?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WebhookOut */
        WebhookOut: {
            /** Apply Policy */
            apply_policy: string;
            /** Enabled */
            enabled: boolean;
            /** Redo Ocr */
            redo_ocr: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_api_audit_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                kind?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeOut"];
                };
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeOut"];
                };
            };
        };
    };
    list_correspondents_api_entities_correspondents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"][];
                };
            };
        };
    };
    list_document_types_api_entities_document_types_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"][];
                };
            };
        };
    };
    list_documents_api_entities_documents_get: {
        parameters: {
            query?: {
                query?: string | null;
                tag_id?: number | null;
                correspondent_id?: number | null;
                document_type_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentSearchPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_entities_documents__doc_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thumbnail_api_entities_documents__doc_id__thumb_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doc_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_storage_paths_api_entities_storage_paths_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"][];
                };
            };
        };
    };
    list_tags_api_entities_tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"][];
                };
            };
        };
    };
    get_merge_candidates_api_entities__entity_type__merge_candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MergeCandidateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_api_entities__entity_type___entity_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_type: string;
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_instructions_api_entities__entity_type___entity_id__instructions_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_type: string;
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstructionsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstructionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_job_api_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    get_prefs_api_prefs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrefsOut"];
                };
            };
        };
    };
    put_prefs_api_prefs_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrefsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrefsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_proposals_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["ProposalStatus"] | null;
                session_id?: number | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_api_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_proposal_api_proposals__proposal_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProposalPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    apply_api_proposals__proposal_id__apply_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_api_proposals__proposal_id__revert_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revert_check_api_proposals__proposal_id__revert_check_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RevertCheckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_sessions_get: {
        parameters: {
            query?: {
                entity_type?: string | null;
                entity_id?: number | null;
                archived?: boolean;
                unfinished?: boolean;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_document_api_sessions_analyze_document__document_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalyzeRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_entity_api_sessions_analyze__entity_type___entity_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entity_type: string;
                entity_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AnalyzeEntityRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_detail_api_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_session_api_sessions__session_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_events_api_sessions__session_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    send_message_api_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ocr_review_api_sessions__session_id__ocr_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OcrReviewOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redo_step_api_sessions__session_id__steps__step_id__redo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                step_id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RedoRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_step_api_sessions__session_id__steps__step_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                step_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_step_api_sessions__session_id__steps__step_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
                step_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StepOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_session_api_sessions__session_id__unarchive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_overview_api_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsOut"];
                };
            };
        };
    };
    stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
    sync_status_api_sync_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncStatusOut"];
                };
            };
        };
    };
    paperless_webhook_api_webhooks_paperless_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
