"""queue attempt log

Revision ID: 21bd21ea21c2
Revises: ca8fde2edc3f
Create Date: 2026-07-17 16:28:41.955387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '21bd21ea21c2'
down_revision: Union[str, Sequence[str], None] = 'ca8fde2edc3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_log', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.drop_column('attempt_log')

    # ### end Alembic commands ###
