"""audit actor

Revision ID: 505d8dcbd080
Revises: 4f2c2bec2232
Create Date: 2026-07-17 17:44:04.098618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '505d8dcbd080'
down_revision: Union[str, Sequence[str], None] = '4f2c2bec2232'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor', sa.String(length=100), nullable=False, server_default='system'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('actor')

    # ### end Alembic commands ###
