"""entity instructions

Revision ID: 79a30929853e
Revises: 505d8dcbd080
Create Date: 2026-07-17 18:19:31.547861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a30929853e'
down_revision: Union[str, Sequence[str], None] = '505d8dcbd080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_instructions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_instructions', schema=None) as batch_op:
        batch_op.create_index('ix_entity_instructions_key', ['entity_type', 'entity_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_instructions', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_instructions_key')

    op.drop_table('entity_instructions')
    # ### end Alembic commands ###
