"""prompt tuning

Revision ID: 8b060a18b1bd
Revises: 8f1d9a92e445
Create Date: 2026-07-18 08:45:07.667557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b060a18b1bd'
down_revision: Union[str, Sequence[str], None] = '8f1d9a92e445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt_fingerprint', sa.String(length=16), nullable=False, server_default=''))

    with op.batch_alter_table('user_prefs', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_prefs', schema=None) as batch_op:
        batch_op.alter_column('value',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.drop_column('prompt_fingerprint')

    # ### end Alembic commands ###
