"""m3-m4 queue, entity embeddings

Revision ID: ac703fe5c011
Revises: be2f530fc15c
Create Date: 2026-07-17 15:43:07.879409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac703fe5c011'
down_revision: Union[str, Sequence[str], None] = 'be2f530fc15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('vector', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_embeddings', schema=None) as batch_op:
        batch_op.create_index('ix_entity_embeddings_key', ['entity_type', 'entity_id'], unique=True)

    op.create_table('queue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lane', sa.Enum('interactive', 'batch', name='queuelane', native_enum=False), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('args', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.Enum('pending', 'running', 'done', 'failed', 'cancelled', name='queuestate', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.create_index('ix_queue_claim', ['state', 'lane', 'id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.drop_index('ix_queue_claim')

    op.drop_table('queue_items')
    with op.batch_alter_table('entity_embeddings', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_embeddings_key')

    op.drop_table('entity_embeddings')
    # ### end Alembic commands ###
