"""retry scheduling, ocr timings

Revision ID: ca8fde2edc3f
Revises: ac703fe5c011
Create Date: 2026-07-17 16:10:01.125629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca8fde2edc3f'
down_revision: Union[str, Sequence[str], None] = 'ac703fe5c011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))

    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.drop_column('scheduled_at')

    with op.batch_alter_table('ocr_results', schema=None) as batch_op:
        batch_op.drop_column('timings')

    # ### end Alembic commands ###
