"""steps replace queue items

Revision ID: dadcfd237bb6
Revises: d698393ec8a9
Create Date: 2026-07-17 16:49:38.260593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'dadcfd237bb6'
down_revision: Union[str, Sequence[str], None] = 'd698393ec8a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('ocr', 'analysis', 'chat', name='stepkind', native_enum=False), nullable=False),
    sa.Column('input', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('state', sa.Enum('pending', 'running', 'awaiting_user', 'succeeded', 'failed', 'superseded', 'cancelled', name='stepstate', native_enum=False), nullable=False),
    sa.Column('lane', sa.Enum('interactive', 'batch', name='queuelane', native_enum=False), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['supersedes_id'], ['steps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.create_index('ix_steps_claim', ['state', 'lane', 'id'], unique=False)
        batch_op.create_index('ix_steps_session', ['session_id', 'id'], unique=False)

    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_claim'))

    op.drop_table('queue_items')
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_proposals_step_id', 'steps', ['step_id'], ['id'])

    # ### end Alembic commands ###

    # ---- backfill: synthesize steps for legacy sessions ---------------
    import json as _json

    bind = op.get_bind()
    sessions = bind.execute(sa.text(
        "SELECT id, params, phase, status, error, message_history, job_id "
        "FROM sessions"
    )).fetchall()
    for row in sessions:
        sid, params_raw, phase, status, error, history_raw, job_id = row
        params = _json.loads(params_raw) if isinstance(params_raw, str) else (params_raw or {})
        history = _json.loads(history_raw) if isinstance(history_raw, str) else (history_raw or [])
        lane = "batch" if job_id is not None else "interactive"
        failed = status == "failed"

        def _insert(kind, state, input_, result):
            bind.execute(
                sa.text(
                    "INSERT INTO steps (session_id, kind, input, state, lane, "
                    "result, error, attempts, attempt_count, max_attempts, "
                    "created_at) VALUES (:sid, :kind, :input, :state, :lane, "
                    ":result, :error, '[]', 1, 3, CURRENT_TIMESTAMP)"
                ),
                {"sid": sid, "kind": kind, "input": _json.dumps(input_),
                 "state": state, "lane": lane,
                 "result": _json.dumps(result),
                 "error": error if state == "failed" else None},
            )
            return bind.execute(sa.text("SELECT max(id) FROM steps")).scalar()

        if params.get("redo_ocr"):
            gate = params.get("ocr_gate")
            if gate:
                ocr_state = "succeeded"
            elif phase == "ocr_review":
                ocr_state = "awaiting_user"
            elif failed and phase in ("queued", "ocr_running"):
                ocr_state = "failed"
            else:
                ocr_state = "succeeded"
            _insert("ocr", ocr_state, {},
                    {"resolution": gate} if gate else {})
        if history or phase in ("analyzing", "done") or (not params.get("redo_ocr")):
            if phase == "done" and not failed:
                a_state = "succeeded"
            elif failed and phase in ("analyzing", "done", "queued"):
                a_state = "failed"
            elif phase in ("ocr_review", "ocr_running"):
                a_state = None  # not started yet
            else:
                a_state = "succeeded" if history else "pending"
            if a_state:
                step_id = _insert(
                    "analysis", a_state, {},
                    {"message_range": [0, len(history)]},
                )
                bind.execute(
                    sa.text(
                        "UPDATE proposals SET step_id = :step WHERE "
                        "session_id = :sid AND kind != 'replace_content'"
                    ),
                    {"step": step_id, "sid": sid},
                )
    # ### end backfill ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proposals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('step_id')

    op.create_table('queue_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('lane', sa.VARCHAR(length=11), nullable=False),
    sa.Column('stage', sa.VARCHAR(length=50), nullable=False),
    sa.Column('args', sqlite.JSON(), nullable=False),
    sa.Column('state', sa.VARCHAR(length=9), nullable=False),
    sa.Column('attempts', sa.INTEGER(), nullable=False),
    sa.Column('max_attempts', sa.INTEGER(), nullable=False),
    sa.Column('session_id', sa.INTEGER(), nullable=True),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('error', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('started_at', sa.DATETIME(), nullable=True),
    sa.Column('finished_at', sa.DATETIME(), nullable=True),
    sa.Column('scheduled_at', sa.DATETIME(), nullable=True),
    sa.Column('attempt_log', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('queue_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_claim'), ['state', 'lane', 'id'], unique=False)

    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_index('ix_steps_session')
        batch_op.drop_index('ix_steps_claim')

    op.drop_table('steps')
    # ### end Alembic commands ###
